USE playlist;

INSERT INTO paises (nombre, iso2) VALUES
  ("Afganistán","AF"),
  ("Albania","AL"),
  ("Alemania","DE"),
  ("Andorra","AD"),
  ("Angola","AO"),
  ("Anguila","AI"),
  ("Antártida","AQ"),
  ("Antigua y Barbuda","AG"),
  ("Arabia Saudita","SA"),
  ("Argelia","DZ"),
  ("Argentina","AR"),
  ("Armenia","AM"),
  ("Aruba","AW"),
  ("Australia","AU"),
  ("Austria","AT"),
  ("Azerbaiyán","AZ"),
  ("Bélgica","BE"),
  ("Bahamas","BS"),
  ("Bahrein","BH"),
  ("Bangladesh","BD"),
  ("Barbados","BB"),
  ("Belice","BZ"),
  ("Benín","BJ"),
  ("Bhután","BT"),
  ("Bielorrusia","BY"),
  ("Birmania","MM"),
  ("Bolivia","BO"),
  ("Bosnia y Herzegovina","BA"),
  ("Botsuana","BW"),
  ("Brasil","BR"),
  ("Brunéi","BN"),
  ("Bulgaria","BG"),
  ("Burkina Faso","BF"),
  ("Burundi","BI"),
  ("Cabo Verde","CV"),
  ("Camboya","KH"),
  ("Camerún","CM"),
  ("Canadá","CA"),
  ("Chad","TD"),
  ("Chile","CL"),
  ("China","CN"),
  ("Chipre","CY"),
  ("Ciudad del Vaticano","VA"),
  ("Colombia","CO"),
  ("Comoras","KM"),
  ("República del Congo","CG"),
  ("República Democrática del Congo","CD"),
  ("Corea del Norte","KP"),
  ("Corea del Sur","KR"),
  ("Costa de Marfil","CI"),
  ("Costa Rica","CR"),
  ("Croacia","HR"),
  ("Cuba","CU"),
  ("Curazao","CW"),
  ("Dinamarca","DK"),
  ("Dominica","DM"),
  ("Ecuador","EC"),
  ("Egipto","EG"),
  ("El Salvador","SV"),
  ("Emiratos Árabes Unidos","AE"),
  ("Eritrea","ER"),
  ("Eslovaquia","SK"),
  ("Eslovenia","SI"),
  ("España","ES"),
  ("Estados Unidos de América","US"),
  ("Estonia","EE"),
  ("Etiopía","ET"),
  ("Filipinas","PH"),
  ("Finlandia","FI"),
  ("Fiyi","FJ"),
  ("Francia","FR"),
  ("Gabón","GA"),
  ("Gambia","GM"),
  ("Georgia","GE"),
  ("Ghana","GH"),
  ("Gibraltar","GI"),
  ("Granada","GD"),
  ("Grecia","GR"),
  ("Groenlandia","GL"),
  ("Guadalupe","GP"),
  ("Guam","GU"),
  ("Guatemala","GT"),
  ("Guayana Francesa","GF"),
  ("Guernsey","GG"),
  ("Guinea","GN"),
  ("Guinea Ecuatorial","GQ"),
  ("Guinea-Bissau","GW"),
  ("Guyana","GY"),
  ("Haití","HT"),
  ("Honduras","HN"),
  ("Hong kong","HK"),
  ("Hungría","HU"),
  ("India","IN"),
  ("Indonesia","ID"),
  ("Irán","IR"),
  ("Irak","IQ"),
  ("Irlanda","IE"),
  ("Isla Bouvet","BV"),
  ("Isla de Man","IM"),
  ("Isla de Navidad","CX"),
  ("Isla Norfolk","NF"),
  ("Islandia","IS"),
  ("Islas Bermudas","BM"),
  ("Islas Caimán","KY"),
  ("Islas Cocos (Keeling)","CC"),
  ("Islas Cook","CK"),
  ("Islas de Åland","AX"),
  ("Islas Feroe","FO"),
  ("Islas Georgias del Sur y Sandwich del Sur","GS"),
  ("Islas Heard y McDonald","HM"),
  ("Islas Maldivas","MV"),
  ("Islas Malvinas","FK"),
  ("Islas Marianas del Norte","MP"),
  ("Islas Marshall","MH"),
  ("Islas Pitcairn","PN"),
  ("Islas Salomón","SB"),
  ("Islas Turcas y Caicos","TC"),
  ("Islas Ultramarinas Menores de Estados Unidos","UM"),
  ("Islas Vírgenes Británicas","VG"),
  ("Islas Vírgenes de los Estados Unidos","VI"),
  ("Israel","IL"),
  ("Italia","IT"),
  ("Jamaica","JM"),
  ("Japón","JP"),
  ("Jersey","JE"),
  ("Jordania","JO"),
  ("Kazajistán","KZ"),
  ("Kenia","KE"),
  ("Kirguistán","KG"),
  ("Kiribati","KI"),
  ("Kuwait","KW"),
  ("Líbano","LB"),
  ("Laos","LA"),
  ("Lesoto","LS"),
  ("Letonia","LV"),
  ("Liberia","LR"),
  ("Libia","LY"),
  ("Liechtenstein","LI"),
  ("Lituania","LT"),
  ("Luxemburgo","LU"),
  ("México","MX"),
  ("Mónaco","MC"),
  ("Macao","MO"),
  ("Macedônia","MK"),
  ("Madagascar","MG"),
  ("Malasia","MY"),
  ("Malawi","MW"),
  ("Mali","ML"),
  ("Malta","MT"),
  ("Marruecos","MA"),
  ("Martinica","MQ"),
  ("Mauricio","MU"),
  ("Mauritania","MR"),
  ("Mayotte","YT"),
  ("Micronesia","FM"),
  ("Moldavia","MD"),
  ("Mongolia","MN"),
  ("Montenegro","ME"),
  ("Montserrat","MS"),
  ("Mozambique","MZ"),
  ("Namibia","NA"),
  ("Nauru","NR"),
  ("Nepal","NP"),
  ("Nicaragua","NI"),
  ("Niger","NE"),
  ("Nigeria","NG"),
  ("Niue","NU"),
  ("Noruega","NO"),
  ("Nueva Caledonia","NC"),
  ("Nueva Zelanda","NZ"),
  ("Omán","OM"),
  ("Países Bajos","NL"),
  ("Pakistán","PK"),
  ("Palau","PW"),
  ("Palestina","PS"),
  ("Panamá","PA"),
  ("Papúa Nueva Guinea","PG"),
  ("Paraguay","PY"),
  ("Perú","PE"),
  ("Polinesia Francesa","PF"),
  ("Polonia","PL"),
  ("Portugal","PT"),
  ("Puerto Rico","PR"),
  ("Qatar","QA"),
  ("Reino Unido","GB"),
  ("República Centroafricana","CF"),
  ("República Checa","CZ"),
  ("República Dominicana","DO"),
  ("República de Sudán del Sur","SS"),
  ("Reunión","RE"),
  ("Ruanda","RW"),
  ("Rumanía","RO"),
  ("Rusia","RU"),
  ("Sahara Occidental","EH"),
  ("Samoa","WS"),
  ("Samoa Americana","AS"),
  ("San Bartolomé","BL"),
  ("San Cristóbal y Nieves","KN"),
  ("San Marino","SM"),
  ("San Martín (Francia)","MF"),
  ("San Pedro y Miquelón","PM"),
  ("San Vicente y las Granadinas","VC"),
  ("Santa Elena","SH"),
  ("Santa Lucía","LC"),
  ("Santo Tomé y Príncipe","ST"),
  ("Senegal","SN"),
  ("Serbia","RS"),
  ("Seychelles","SC"),
  ("Sierra Leona","SL"),
  ("Singapur","SG"),
  ("Sint Maarten","SX"),
  ("Siria","SY"),
  ("Somalia","SO"),
  ("Sri lanka","LK"),
  ("Sudáfrica","ZA"),
  ("Sudán","SD"),
  ("Suecia","SE"),
  ("Suiza","CH"),
  ("Surinám","SR"),
  ("Svalbard y Jan Mayen","SJ"),
  ("Swazilandia","SZ"),
  ("Tayikistán","TJ"),
  ("Tailandia","TH"),
  ("Taiwán","TW"),
  ("Tanzania","TZ"),
  ("Territorio Británico del Océano Índico","IO"),
  ("Territorios Australes y Antárticas Franceses","TF"),
  ("Timor Oriental","TL"),
  ("Togo","TG"),
  ("Tokelau","TK"),
  ("Tonga","TO"),
  ("Trinidad y Tobago","TT"),
  ("Tunez","TN"),
  ("Turkmenistán","TM"),
  ("Turquía","TR"),
  ("Tuvalu","TV"),
  ("Ucrania","UA"),
  ("Uganda","UG"),
  ("Uruguay","UY"),
  ("Uzbekistán","UZ"),
  ("Vanuatu","VU"),
  ("Venezuela","VE"),
  ("Vietnam","VN"),
  ("Wallis y Futuna","WF"),
  ("Yemen","YE"),
  ("Yibuti","DJ"),
  ("Zambia","ZM"),
  ("Zimbabue","ZW");
 
 SELECT * FROM paises WHERE iso2 = "DE";

/*65 US*/
  INSERT INTO generos (nombre, instrumentación, pais) VALUES
  ("Pop", "Guitarra y bajo", 65),
  ("Jazz", "Trompeta y saxofón", 65),
  ("Hip-hop", "Sinterizados y tocadiscos", 65),
  ("Electropop", "Teclado y violín", 3),
  ("Rock", "Bajo y batería", 65);
  

INSERT INTO artistas (nombre, nombre_de_nacimiento, fecha_de_nacimiento, año_de_inicio, pais, genero) VALUES
  ("John Legend", "John Roger Stephens", "1978-12-28","2001",65, 1),
  ("Michael Jackson", "Michael Joseph Jackson", "1958-08-29", "1964", 65,	2),
  ("Zara Larsson", "Zara Maria Larsson", "1997-12-16", "2008", 214, 3),
  ("Eminem", "Marshall Bruce Mathers III", "1972-10-17", "1988", 65, 4),
  ("Ellie Goulding", "Elena Jane Goulding", "1986-12-30", "2007", 214, 5);


INSERT INTO discos (nombre, fecha_de_lanzamiento, cantidad_de_canciones, artista) VALUES
  ("Love in the future", "2013-08-30", 16 ,1),
  ("Bad", "1987-08-31", 11 ,2),
  ("So Good", "2017-03-17", 15 ,3),
  ("Encore", "2004-11-12", 23 ,4),
  ("Halcyon", "2017-08-05", 18 ,5);


INSERT INTO canciones (nombre, duracion, disco ) VALUES
  ("Green Light", 341, 1),
  ("Smooth Criminal", 256, 2),
  ("WOW", 180, 3),
  ("Venom", 295, 4),
  ("Return to love", 272, 5);

